homeassistant:
  customize:
    group.weather_tab:
      order: 1

sensor:
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
  - platform: season
  - platform: template
    sensors:
      weekday:
        friendly_name: 'Weekday'
        value_template: '{{ now().strftime("%A") }}'
      forecast_0:
        friendly_name: "Today"
        entity_id:
          - sensor.dark_sky_daily_high_temperature_0d
          - sensor.dark_sky_daily_low_temperature_0d
          - sensor.dark_sky_precip_probability_0d
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_0d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_0d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_0d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_0d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_0d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_0d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_0d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_0d", "sleet") %}
            mdi:weather-snowy-rain
          {% elif is_state("sensor.dark_sky_icon_0d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_0d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_0d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_0d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_0d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy            
          {% else %}
            error
          {% endif %}    
      forecast_1:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400)) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_1d
          - sensor.dark_sky_daily_low_temperature_1d
          - sensor.dark_sky_precip_probability_1d
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_1d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_1d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_1d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_1d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_1d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_1d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_1d", "sleet") %}
            mdi:weather-snowy-rain
          {% elif is_state("sensor.dark_sky_icon_1d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_1d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_1d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_1d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_1d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy            
          {% else %}
            error
          {% endif %}

      forecast_2:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *2) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_2d
          - sensor.dark_sky_daily_low_temperature_2d
          - sensor.dark_sky_precip_probability_2d
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_2d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_2d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_2d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_2d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_2d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_2d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_2d", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.dark_sky_icon_2d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_2d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_2d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_2d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_2d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy            
          {% else %}
            error
          {% endif %}
                 
      forecast_3:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *3) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_3d
          - sensor.dark_sky_daily_low_temperature_3d
          - sensor.dark_sky_precip_probability_3d
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_3d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_3d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_3d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_3d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_3d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_3d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_3d", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.dark_sky_icon_3d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_3d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_3d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_3d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_3d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
        
      forecast_4:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *4) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_4d
          - sensor.dark_sky_daily_low_temperature_4d
          - sensor.dark_sky_precip_probability_4d
        value_template: >          
          {{states.sensor.dark_sky_daily_high_temperature_4d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_4d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_4d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_4d", "clear-night") %}
            mdi:weather-night            
          {% elif is_state("sensor.dark_sky_icon_4d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_4d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_4d", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.dark_sky_icon_4d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_4d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_4d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_4d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_4d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}

      forecast_5:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *5) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_5d
          - sensor.dark_sky_daily_low_temperature_5d
          - sensor.dark_sky_precip_probability_5d
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_5d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_5d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_5d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_5d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_5d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_5d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_5d", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.dark_sky_icon_5d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_5d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_5d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_5d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_5d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}
           
      forecast_6:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *6) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_6d
          - sensor.dark_sky_daily_low_temperature_6d
          - sensor.dark_sky_precip_probability_6d
        value_template: >          
            {{states.sensor.dark_sky_daily_high_temperature_6d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_6d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_6d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_6d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_6d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_6d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_6d", "sleet") %}
            mdi:weather-snowy-rain  
          {% elif is_state("sensor.dark_sky_icon_6d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_6d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_6d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_6d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_6d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}

      forecast_7:
        friendly_name_template: '{{ (as_timestamp(now()) + (86400) *7) | timestamp_custom("%A", True) }}'
        entity_id:
          - sensor.dark_sky_daily_high_temperature_7d
          - sensor.dark_sky_daily_low_temperature_7d
          - sensor.dark_sky_precip_probability_7d
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_7d.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_7d.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7d.state|round(0)}}%
        icon_template: >-
          {% if is_state("sensor.dark_sky_icon_7d", "clear-day") %}
            mdi:weather-sunny
          {% elif is_state("sensor.dark_sky_icon_7d", "clear-night") %}
            mdi:weather-night
          {% elif is_state("sensor.dark_sky_icon_7d", "cloudy") %}
            mdi:weather-cloudy   
          {% elif is_state("sensor.dark_sky_icon_7d", "rain") %}
            mdi:weather-pouring        
          {% elif is_state("sensor.dark_sky_icon_7d", "sleet") %}
            mdi:weather-snowy-rain 
          {% elif is_state("sensor.dark_sky_icon_7d", "snow") %}
            mdi:weather-snowy
          {% elif is_state("sensor.dark_sky_icon_7d", "wind") %}
            mdi:weather-windy
          {% elif is_state("sensor.dark_sky_icon_7d", "fog") %}
            mdi:weather-fog
          {% elif is_state("sensor.dark_sky_icon_7d", "partly-cloudy-day") %}
            mdi:weather-partlycloudy
          {% elif is_state("sensor.dark_sky_icon_7d", "partly-cloudy-night") %}
            mdi:weather-partlycloudy
          {% else %}
            error
          {% endif %}

group:
  weather_tab:
    name: Weather
    # icon: mdi:weather-sunset
    view: yes
    entities:
    - group.weather_info
    - group.weather_forecast
    - group.air_quality
  weather_info:
    name: Current Conditions
    view: no
    entities:
      - sun.sun
      - sensor.season
      - sensor.dark_sky_summary
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_type
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_cloud_cover
      - sensor.dark_sky_humidity
  weather_forecast:
    name: Forecast
    view: no
    icon: mdi:sun
    entities:
      - sensor.forecast_0
      - sensor.forecast_1
      - sensor.forecast_2
      - sensor.forecast_3
      - sensor.forecast_4
      - sensor.forecast_5
      - sensor.forecast_6
      - sensor.forecast_7